apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oauth2

resources:
  - namespace.yaml
  - configmap.yaml
  - auth-server-deployment.yaml
  - auth-server-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: oauth2-system

images:
  - name: ghcr.io/your-org/oauth2/auth-server
    newTag: latest
